Feature/integrate sql server
Parsa2820/Polaris-MSSQL pull request #1
Opened 2020-10-22 11:44 UTC by Parsa2820

Ready for filter implementation

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database.Test/Communication/MicrosoftSqlServer/MSqlHandlerTest.cs
> +            MSqlClientFactory.GetInstance().CreateInitialClient("Data Source=(local);Initial Catalog=Star;Integrated Security=True;");
بهتره از
const string
استفاده بشه.

دوتای بعدیش هم همینطور

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database.Test/UnitTest1.cs
> +}
اگه اضافه هست حذف کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/Elastic/Nest/NestEntityHandler.cs
> +            //return response.ToList()[0] as TModel;
در کل کد رو کامنت کردن کار درستی نیست. 
جاهایی رو که لازم ندارید حذف کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlClientFactory.cs
> +        private static MSqlClientFactory singletonInstance = new MSqlClientFactory();
```csharp
public static MSqlClientFactory Instance { get; } = new MSqlClientFactory();
```
اینجوری بهتره.
دیگه نیازی به تابع
GetInstance()
هم نیست.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlClientFactory.cs
> +        private string client = null;
چرا اینجا
client
به صورت 
string
هست؟

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            command.Dispose();
میتونید از
using
استفاده کنید که لازم نباشه تهش
dispose
رو بنویسید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            }
سعی کنید درگیر آرایه نشید. از لیست استفاده کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            connection.Close();
https://stackoverflow.com/questions/744051/is-it-necessary-to-manually-close-and-dispose-of-sqldatareader

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            return result;
نمیشه از همون تابع بالایی استفاده کرد؟
مثلا اینجوری
```csharp
public TModel GetEntity(TType id, string sourceName) => 
      GetEntities(new TType[] { id }, sourceName).First();
```

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            Insert(newEntity, sourceName);
اینجا بهتر نیست خود کوئری آپدیت رو پیاده کنید؟
الان داره 2 تا کوئری اجرا میکنه.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +            DataTable dataTable = new DataTable();
سعی کنید همه جا از
var 
استفاده کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +            var queryString = $"SELECT * FROM {sourceName}";
https://medium.com/better-programming/using-select-in-an-sql-query-is-a-bad-practice-a8f6beeca1da

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +        }
الان یکم دوپلیکت وجود داره.
مثلا با تابع 
GetEntities(TType[] ids, string sourceName)

پیشنهاد من اینه که اون قسمتی که داره کوئری رو
Execute
میکنه و نتایجش رو میریزه تو لیست رو جدا کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Validation/MicrosoftSqlServer/MicrosoftSqlTableValidator.cs
> +                return;
اضافه است.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Validation/MicrosoftSqlServer/MicrosoftSqlTableValidator.cs
> +            var connection = new SqlConnection(connectionString);
این رو باید
Dispose
کنید.

2020-10-24 17:31 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlClientFactory.cs
> +        private string client = null;
یه جورایی مفهوم
ConnectionString
رو نمیرسونه.

2020-10-24 17:35 UTC, hbehboudi requested changes
.

2020-10-26 14:22 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/Elastic/Nest/NestEntityHandler.cs
> +            //return response.ToList()[0] as TModel;
حل شد.

2020-10-26 14:36 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlClientFactory.cs
> +        private string client = null;
<p dir="rtl">
آره ولی wrapper پیدا نکردم. چی باشه بهتره؟
</p>

2020-10-26 14:48 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            return result;
اوکی شد

2020-10-26 14:54 UTC, Parsa2820 commented on Back end/Polaris/Database/Validation/MicrosoftSqlServer/MicrosoftSqlTableValidator.cs
> +                return;
<p dir="rtl">
واسه این گذاشتم که موقع insert اگه table وجود نداشت الکی query رو نسازه.
</p>

2020-10-26 15:05 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +        }
یه تابع ازش تو 
MSqlHandler
اکسترکت شد

2020-10-26 15:13 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            Insert(newEntity, sourceName);
اونجوری فکر کنم باید یه بار بگیریمش ببینیم کدوم فیلدا تغییر کرده بعد کوئری آپدیت بزنیم. بازم دو بار میشه.

2020-10-26 15:43 UTC, Parsa2820 commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +            var queryString = $"SELECT * FROM {sourceName}";
مقاله خوب بود. درستش کردم.

2020-10-28 07:07 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlClientFactory.cs
> +        private string client = null;
دقیقا نمیدونم. همین اوکیه.

2020-10-28 07:08 UTC, hbehboudi commented on Back end/Polaris/Database/Validation/MicrosoftSqlServer/MicrosoftSqlTableValidator.cs
> +                return;
return
رو منظورمه.

2020-10-28 08:03 UTC, hbehboudi approved these changes
بسیار عالی👌👌👌

2020-10-28 08:03 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlEntityHandler.cs
> +            Insert(newEntity, sourceName);
لازم نیست دقیقا ببینی کدوم فیلد تغییر کرده.
کل فیلدها رو میتونی آپدیت کنی.

2020-10-28 08:03 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +        }
```csharp
private void InitTableColumns() => 
      tableColumns = string.Join(", ", typeof(TModel).GetProperties().Select(x => x.Name));
```

2020-10-28 08:03 UTC, hbehboudi commented on Back end/Polaris/Database/Communication/MicrosoftSqlServer/MSqlHandler.cs
> +        }
از قابلیت
using declarations
استفاده کنید. البته برای
C# 8
هست. پروژتون رو باید آپدیت کنید. اینجوری خیلی تمیزتر میشه.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using

2020-10-28 13:02 UTC, Parsa2820 commented on Back end/Polaris/Database/Validation/MicrosoftSqlServer/MicrosoftSqlTableValidator.cs
> +                return;
آهان درست کردم

2020-11-05 10:20 UTC, merged